name: monkeyinaround
favicon: null
layout_spectrum: 0.29681
typography_spectrum: 0.03723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#c5d0d1'
    - '#4d4a3f'
    - '#718b89'
    - '#fefefe'
  brandStrength: 0.3125
  lightness: 0.872435140889138
  saturation: 0.5625
  rhythmicContrast: 0.8342297524213791
purpose: []
