name: monkeyinaround
favicon: null
layout_spectrum: 0.09573
typography_spectrum: 0.25397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c3242'
    - '#fbfbfb'
    - '#9f8c88'
    - '#d2aaa0'
    - '#4a7198'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
