name: monkeyinaround
favicon: null
layout_spectrum: 0.29681
typography_spectrum: 0.25397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7ffff'
    - '#000000'
    - '#aec08c'
    - '#3a5951'
    - '#52a134'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
